# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-09 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvimporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='csv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
